# Generated by Django 3.1.13 on 2021-09-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0002_auto_20210905_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give',
            name='category',
            field=models.CharField(blank=True, choices=[('furniture', 'Furniture'), ('clothe', 'Clothes'), ('shoe', 'Shoes'), ('toy', 'toys'), ('electronics', 'Electronics'), ('bags', 'Bags'), ('mobile', 'mobile-phones'), ('laptop', 'Laptops'), ('book', 'Books'), ('kitchen-utensils', 'Kitchen-utensils'), ('bicycle', 'Bicyle'), ('accessories', 'Accessories'), ('food-stuffs', 'Food-stuffs'), ('groceries', 'Groceries'), ('generator', 'Generator'), ('beauty-product', 'Beauty-product')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='give',
            name='gift_status',
            field=models.CharField(blank=True, choices=[('unpicked', 'unpicked'), ('requested', 'requested'), ('received', 'received')], default='unpicked', max_length=30),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('lagos', 'Lagos'), ('ogun', 'Ogun'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('ondo', 'Ondo'), ('kwara', 'Kwara'), ('niger', 'Niger'), ('nassarawa', 'Nassarawa'), ('plateau', 'Plateau'), ('abuja', 'Abuja'), ('edo', 'Edo'), ('abia', 'Abia'), ('akwa-ibom', 'Akwa-Ibom'), ('adamawa', 'Adamawa'), ('anambra', 'Anambra'), ('cross-river', 'Cross-River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('benue', 'Benue'), ('bayelsa', 'Bayelsa'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('jigawa', 'Jigawa'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kogi', 'Kogi'), ('kebbi', 'Kebbi'), ('kaduna', 'Kaduna'), ('imo', 'Imo'), ('borno', 'Borno'), ('gombe', 'Gombe'), ('rivers', 'Rivers'), ('zamfara', 'Zamfara'), ('yobe', 'Yobe'), ('sokoto', 'Sokoto')], default='', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('clothe', 'Clothes'), ('shoe', 'Shoes'), ('toy', 'toys'), ('electronics', 'Electronics'), ('bags', 'Bags'), ('mobile', 'mobile-phones'), ('laptop', 'Laptops'), ('book', 'Books'), ('kitchen-utensils', 'Kitchen-utensils'), ('bicycle', 'Bicyle'), ('accessories', 'Accessories'), ('food-stuffs', 'Food-stuffs'), ('groceries', 'Groceries'), ('generator', 'Generator'), ('beauty-product', 'Beauty-product')], max_length=100)),
                ('giver_number', models.IntegerField(blank=True, null=True)),
                ('receiver_number', models.IntegerField(blank=True, null=True)),
                ('giver_contacted', models.BooleanField(default=False)),
                ('receiver_contacted', models.BooleanField(default=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='givers.give')),
            ],
        ),
    ]
