# Generated by Django 3.1.13 on 2021-09-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0003_auto_20210905_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(choices=[('courier plus', 'Courier Plus Services Limited'), ('gig logistics', 'GIG Logistics'), ('ags movers', 'AGS Movers'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('gat logistics', 'GAT Logistics')], default='', max_length=100),
        ),
    ]
