# Generated by Django 3.1.13 on 2021-09-07 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('givers', '0004_vendor_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='givers.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='received',
            name='gift_requested',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commodity', to='givers.give'),
        ),
        migrations.AlterField(
            model_name='received',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift', to='givers.give'),
        ),
    ]
