# Generated by Django 3.1.7 on 2021-09-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0005_auto_20210907_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='giver_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='give',
            name='phone_number',
            field=models.IntegerField(default=8181267583),
        ),
        migrations.AddField(
            model_name='vendor',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='car1.jpg', upload_to='givers/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift', to='givers.give'),
        ),
    ]
