# Generated by Django 3.1.7 on 2021-09-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0007_auto_20210908_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='gift',
            new_name='give',
        ),
        migrations.RemoveField(
            model_name='give',
            name='gift_recipient',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
    ]
