# Generated by Django 3.1.7 on 2021-09-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0008_auto_20210909_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='gift_recipient',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
