# Generated by Django 3.1.7 on 2021-09-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0009_give_gift_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='give',
            old_name='phone_number',
            new_name='giver_number',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='phone_number',
            new_name='giver_number',
        ),
    ]
