# Generated by Django 3.1.13 on 2021-09-13 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('givers', '0010_auto_20210909_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='delivery_address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
