# Generated by Django 3.1.13 on 2021-09-13 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('givers', '0011_auto_20210913_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='prof',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='give', to='givers.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='give',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
