# Generated by Django 3.1.7 on 2021-09-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0014_auto_20210923_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
