# Generated by Django 3.1.7 on 2021-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0015_auto_20210927_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pic.jpg', upload_to='givers/images'),
        ),
    ]
