# Generated by Django 3.1.13 on 2021-10-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0017_auto_20211001_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give',
            name='giver_number',
            field=models.BigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(default=8000000000),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='giver_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='receiver_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
