# Generated by Django 3.1.13 on 2021-10-11 22:04

from django.db import migrations, models
import givers.models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0019_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(default=8000000000, validators=[givers.models.validate_num]),
        ),
    ]
