# Generated by Django 3.1.13 on 2021-10-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0020_auto_20211011_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(default=8000000000),
        ),
    ]
