# Generated by Django 3.1.13 on 2021-10-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0021_auto_20211011_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('lagos', 'Lagos'), ('ogun', 'Ogun'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('ondo', 'Ondo'), ('kwara', 'Kwara'), ('niger', 'Niger'), ('nassarawa', 'Nassarawa'), ('plateau', 'Plateau'), ('abuja', 'Abuja'), ('edo', 'Edo'), ('abia', 'Abia'), ('akwa-ibom', 'Akwa-Ibom'), ('adamawa', 'Adamawa'), ('anambra', 'Anambra'), ('cross-river', 'Cross-River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('benue', 'Benue'), ('bayelsa', 'Bayelsa'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('jigawa', 'Jigawa'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kogi', 'Kogi'), ('kebbi', 'Kebbi'), ('kaduna', 'Kaduna'), ('imo', 'Imo'), ('borno', 'Borno'), ('gombe', 'Gombe'), ('rivers', 'Rivers'), ('zamfara', 'Zamfara'), ('yobe', 'Yobe'), ('sokoto', 'Sokoto')], default='', max_length=50),
        ),
    ]
